export const anggotaList = [
  {
    id: 1,
    nama: "H. Ahmad Sudrajat, S.E.",
    pangkat: "Penasihat / Pelindung",
    initials: "AS",
    color: "from-emerald-500 to-teal-700",
  },
  {
    id: 2,
    nama: "Budi Santoso, S.Pt.",
    pangkat: "Direktur Utama BUMDes",
    initials: "BS",
    color: "from-green-600 to-emerald-800",
  },
  {
    id: 3,
    nama: "Hj. Siti Rahmawati",
    pangkat: "Sekretaris BUMDes",
    initials: "SR",
    color: "from-teal-500 to-green-700",
  },
  {
    id: 4,
    nama: "Dewi Lestari, A.Md.",
    pangkat: "Bendahara BUMDes",
    initials: "DL",
    color: "from-emerald-600 to-green-800",
  },
  {
    id: 5,
    nama: "Eko Prasetyo",
    pangkat: "Manajer Unit Sport Center",
    initials: "EP",
    color: "from-cyan-600 to-blue-700",
  },
  {
    id: 6,
    nama: "Irwan Setiawan",
    pangkat: "Manajer Unit Pertanian",
    initials: "IS",
    color: "from-lime-600 to-emerald-700",
  },
  {
    id: 7,
    nama: "Rina Kartika, S.T.",
    pangkat: "Manajer Unit Pengolahan Sampah",
    initials: "RK",
    color: "from-green-700 to-teal-800",
  },
  {
    id: 8,
    nama: "Bambang Supriyadi",
    pangkat: "Pengawas BUMDes",
    initials: "BS",
    color: "from-slate-600 to-gray-800",
  },
  {
    id: 9,
    nama: "Agus Cahyono",
    pangkat: "Staf Operasional & Logistik",
    initials: "AC",
    color: "from-emerald-500 to-emerald-700",
  },
  {
    id: 10,
    nama: "Sri Wahyuni",
    pangkat: "Staf Administrasi",
    initials: "SW",
    color: "from-teal-600 to-cyan-800",
  },
  {
    id: 11,
    nama: "Hendra Gunawan",
    pangkat: "Pengelola Unit Peternakan",
    initials: "HG",
    color: "from-green-600 to-emerald-700",
  },
  {
    id: 12,
    nama: "Tri Mulyani",
    pangkat: "Staf Pemasaran & UMKM",
    initials: "TM",
    color: "from-emerald-700 to-green-900",
  },
];
