export const asetData = {
  "2025": [
    {
      id: 1,
      barang: "Tanah BUMDes (Kas Desa)",
      jumlah: "1x",
      harga: 200000000,
      hargaDisplay: "200jt",
      kondisi: "Baik",
    },
    {
      id: 2,
      barang: "Bangunan Gedung Sekretariat",
      jumlah: "1 Unit",
      harga: 150000000,
      hargaDisplay: "150jt",
      kondisi: "Baik",
    },
    {
      id: 3,
      barang: "Fasilitas Sport Center",
      jumlah: "1 Set",
      harga: 75000000,
      hargaDisplay: "75jt",
      kondisi: "Baik",
    },
    {
      id: 4,
      barang: "Mesin Traktor Pertanian",
      jumlah: "2 Unit",
      harga: 30000000,
      hargaDisplay: "30jt",
      kondisi: "Baik",
    },
    {
      id: 5,
      barang: "Motor Pengangkut Sampah Roda 3",
      jumlah: "2 Unit",
      harga: 25000000,
      hargaDisplay: "25jt",
      kondisi: "Rusak",
    },
    {
      id: 6,
      barang: "Perangkat Komputer & Printer Kantor",
      jumlah: "3 Set",
      harga: 12000000,
      hargaDisplay: "12jt",
      kondisi: "Baik",
    },
  ],
  "2026": [
    {
      id: 1,
      barang: "Tanah BUMDes (Kas Desa)",
      jumlah: "1x",
      harga: 220000000,
      hargaDisplay: "220jt",
      kondisi: "Baik",
    },
    {
      id: 2,
      barang: "Bangunan Gedung Sekretariat",
      jumlah: "1 Unit",
      harga: 150000000,
      hargaDisplay: "150jt",
      kondisi: "Baik",
    },
    {
      id: 3,
      barang: "Fasilitas Sport Center",
      jumlah: "1 Set",
      harga: 85000000,
      hargaDisplay: "85jt",
      kondisi: "Baik",
    },
    {
      id: 4,
      barang: "Mesin Traktor Pertanian",
      jumlah: "3 Unit",
      harga: 45000000,
      hargaDisplay: "45jt",
      kondisi: "Baik",
    },
    {
      id: 5,
      barang: "Motor Pengangkut Sampah Roda 3",
      jumlah: "3 Unit",
      harga: 38000000,
      hargaDisplay: "38jt",
      kondisi: "Baik",
    },
    {
      id: 6,
      barang: "Timbangan Digital & Mesin Cacah Sampah",
      jumlah: "1 Unit",
      harga: 18000000,
      hargaDisplay: "18jt",
      kondisi: "Baik",
    },
    {
      id: 7,
      barang: "Perangkat Komputer & IT Support",
      jumlah: "4 Set",
      harga: 16000000,
      hargaDisplay: "16jt",
      kondisi: "Baik",
    },
    {
      id: 8,
      barang: "Pompa Air Irigasi Sawah",
      jumlah: "4 Unit",
      harga: 14000000,
      hargaDisplay: "14jt",
      kondisi: "Rusak",
    },
  ],
};
